### ISSUE TITLE
Beggars upgraded into peasants do not return to inventory when removed from field.

### ISSUE THREAD

**Issue by gapatterson** [Rybadour/cards-n-catapults-idle#1]
This occurred after placing a schoolhouse down surrounded by beggars.  They upgraded as expected.  When right clicking them, they did not return to the inventory.  Possibly related: no regular peasant units had been unlocked yet, so the inventory item was not visible yet.

**Comment by gapatterson** [comment]
It appears that once a peasant has been pulled from the stone pack, all the earned/upgraded peasants show up in the list.

**Comment by Rybadour** [comment]
Ah yes, I'm pretty sure I know why that's happening! I'll add it to my personal TODO list. Thank you!
